### = = = TESTING book = = = 

GET http://localhost:8080/api/book
###
DELETE  http://localhost:8080/api/book/602ad72e2e564c70fd74f105
###
GET http://localhost:8080/api/book?title=action
###
POST http://localhost:8080/api/book
Content-Type: application/json

{
    "title": "spring in action 4",
    "price": 20.0,
    "introduction": "....",
    "about": "...",
    "seller": {
        "name": "徽章",
        "contact": "vx： kvimsg",
        "about": "可爱的小哥哥"
    }
}

### = = = TESTING USER = = =
GET http://localhost:8080/api/comment
###
GET http://localhost:8080/api/comment/6037acbbe43cda3b57e17663
###
POST http://localhost:8080/api/comment
Content-Type: application/json

{
    "title": "顶顶顶",
    "content": "书都可以啊 有我想要的",
    "publisher": "爱欢迎的云朵"
}
###
DELETE  http://localhost:8080/api/comment/1




### = = = TESTING USER = = =
###
GET http://localhost:8080/api/currentuser

###
POST http://localhost:8080/api/login
Content-Type: application/json

{
    "phoneNumber": "1001011",
    "password": "cuidan123"
}


### = = = TESTING IMG FILE = = =
GET http://localhost:8080/public/img/603693c738624a6c0e592de2

###
DELETE http://localhost:8080/api/photo/603692dc38624a6c0e592ddf


###
POST http://localhost:8080/api/photo/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="photo"; filename="1.png"
Content-Type: image/png

< C:\Users\CoolBoy\Pictures\girl05.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--