### = = = TESTING book = = = 

GET http://localhost:8080/api/book
###
DELETE  http://localhost:8080/api/book/602ad72e2e564c70fd74f105
###
GET http://localhost:8080/api/book?title=action
###
POST http://localhost:8080/api/book
Content-Type: application/json

{
    "title": "spring in action 4",
    "price": 20.0,
    "introduction": "....",
    "about": "...",
    "seller": {
        "name": "徽章",
        "contact": "vx： kvimsg",
        "about": "可爱的小哥哥"
    }
}

### = = = TESTING USER = = =
###
GET http://localhost:8080/api/currentuser

###
POST http://localhost:8080/api/login
Content-Type: application/json

{
    "phoneNumber": "1001011",
    "password": "cuidan123"
}
